// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffOperationsProvider is an autogenerated mock type for the TinkoffOperationsProvider type
type TinkoffOperationsProvider struct {
	mock.Mock
}

// TinkoffGetOperations provides a mock function with given fields: ctx, opRequest
func (_m *TinkoffOperationsProvider) TinkoffGetOperations(ctx context.Context, opRequest domain.OperationsRequest) ([]domain.Operation, error) {
	ret := _m.Called(ctx, opRequest)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetOperations")
	}

	var r0 []domain.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OperationsRequest) ([]domain.Operation, error)); ok {
		return rf(ctx, opRequest)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OperationsRequest) []domain.Operation); ok {
		r0 = rf(ctx, opRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OperationsRequest) error); ok {
		r1 = rf(ctx, opRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffOperationsProvider creates a new instance of TinkoffOperationsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffOperationsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffOperationsProvider {
	mock := &TinkoffOperationsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
