// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffProvider is an autogenerated mock type for the TinkoffProvider type
type TinkoffProvider struct {
	mock.Mock
}

// TinkoffFindBy provides a mock function with given fields: ctx, query
func (_m *TinkoffProvider) TinkoffFindBy(ctx context.Context, query string) (domain.InstrumentShortList, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffFindBy")
	}

	var r0 domain.InstrumentShortList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.InstrumentShortList, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.InstrumentShortList); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.InstrumentShortList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetAccounts provides a mock function with given fields: ctx
func (_m *TinkoffProvider) TinkoffGetAccounts(ctx context.Context) (map[string]domain.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetAccounts")
	}

	var r0 map[string]domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]domain.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]domain.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetBondByUid provides a mock function with given fields: ctx, uid
func (_m *TinkoffProvider) TinkoffGetBondByUid(ctx context.Context, uid string) (domain.Bond, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetBondByUid")
	}

	var r0 domain.Bond
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Bond, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Bond); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(domain.Bond)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetLastPriceInPersentageToNominal provides a mock function with given fields: ctx, instrumentUid
func (_m *TinkoffProvider) TinkoffGetLastPriceInPersentageToNominal(ctx context.Context, instrumentUid string) (domain.LastPrice, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetLastPriceInPersentageToNominal")
	}

	var r0 domain.LastPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.LastPrice, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.LastPrice); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(domain.LastPrice)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetPortfolio provides a mock function with given fields: ctx, account
func (_m *TinkoffProvider) TinkoffGetPortfolio(ctx context.Context, account domain.Account) (domain.Portfolio, error) {
	ret := _m.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetPortfolio")
	}

	var r0 domain.Portfolio
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) (domain.Portfolio, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account) domain.Portfolio); ok {
		r0 = rf(ctx, account)
	} else {
		r0 = ret.Get(0).(domain.Portfolio)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffProvider creates a new instance of TinkoffProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffProvider {
	mock := &TinkoffProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
