workersNumber: 5
dbType: "postgreSQL" # "postgreSQL" , "SQLite"
serviceStorageSQLLitePath: "/data/sqlite/service_storage.db"
postgresHost:
  sslmode: "disable"
clients:
  tinkoffClient:
  cbrClient:
  moexClient:
  bondReportService:
    bondReportServiceHost: "0.0.0.0"
timeouts:
  http_read_header_timeout: 10s
  http_read_timeout: 10s
  http_write_timeout: 10s
  http_idle_timeout: 60s
  http_shutdown_timeout: 7s
  request_timeout: 5s
  app_close_timeout: 3s
  db_connect_timeout: 5s
