// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "bonds-report-service/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffProvider is an autogenerated mock type for the TinkoffProvider type
type TinkoffProvider struct {
	mock.Mock
}

// TinkoffGetBondActions provides a mock function with given fields: ctx, instrumentUid
func (_m *TinkoffProvider) TinkoffGetBondActions(ctx context.Context, instrumentUid string) (domain.BondIdentIdentifiers, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetBondActions")
	}

	var r0 domain.BondIdentIdentifiers
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.BondIdentIdentifiers, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.BondIdentIdentifiers); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(domain.BondIdentIdentifiers)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetLastPriceInPersentageToNominal provides a mock function with given fields: ctx, instrumentUid
func (_m *TinkoffProvider) TinkoffGetLastPriceInPersentageToNominal(ctx context.Context, instrumentUid string) (domain.LastPrice, error) {
	ret := _m.Called(ctx, instrumentUid)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetLastPriceInPersentageToNominal")
	}

	var r0 domain.LastPrice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.LastPrice, error)); ok {
		return rf(ctx, instrumentUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.LastPrice); ok {
		r0 = rf(ctx, instrumentUid)
	} else {
		r0 = ret.Get(0).(domain.LastPrice)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, instrumentUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffProvider creates a new instance of TinkoffProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffProvider {
	mock := &TinkoffProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
