// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "bonds-report-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TinkoffProvider is an autogenerated mock type for the TinkoffProvider type
type TinkoffProvider struct {
	mock.Mock
}

// TinkoffGetBaseShareFutureValute provides a mock function with given fields: ctx, positionUid
func (_m *TinkoffProvider) TinkoffGetBaseShareFutureValute(ctx context.Context, positionUid string) (domain.ShareCurrency, error) {
	ret := _m.Called(ctx, positionUid)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetBaseShareFutureValute")
	}

	var r0 domain.ShareCurrency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ShareCurrency, error)); ok {
		return rf(ctx, positionUid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ShareCurrency); ok {
		r0 = rf(ctx, positionUid)
	} else {
		r0 = ret.Get(0).(domain.ShareCurrency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, positionUid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetCurrencyBy provides a mock function with given fields: ctx, figi
func (_m *TinkoffProvider) TinkoffGetCurrencyBy(ctx context.Context, figi string) (domain.Currency, error) {
	ret := _m.Called(ctx, figi)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetCurrencyBy")
	}

	var r0 domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Currency, error)); ok {
		return rf(ctx, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Currency); ok {
		r0 = rf(ctx, figi)
	} else {
		r0 = ret.Get(0).(domain.Currency)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TinkoffGetFutureBy provides a mock function with given fields: ctx, figi
func (_m *TinkoffProvider) TinkoffGetFutureBy(ctx context.Context, figi string) (domain.Future, error) {
	ret := _m.Called(ctx, figi)

	if len(ret) == 0 {
		panic("no return value specified for TinkoffGetFutureBy")
	}

	var r0 domain.Future
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Future, error)); ok {
		return rf(ctx, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Future); ok {
		r0 = rf(ctx, figi)
	} else {
		r0 = ret.Get(0).(domain.Future)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTinkoffProvider creates a new instance of TinkoffProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTinkoffProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TinkoffProvider {
	mock := &TinkoffProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
